#!/bin/bash

if which dnf >/dev/null 2>&1 ; then dnf update -y --refresh ; fi
if which yum >/dev/null 2>&1 ; then yum update -y --refresh ; fi

if which apt-get >/dev/null 2>&1
then
    apt-get update
    apt-get upgrade -y
fi

if [[ $1 ]]
then
    init 6 || reboot
fi
